modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "CC0 1.0 Universal"

[[mods]]
modId = "knowledgebooks"
version = "${version}"
displayName = "Knowledge Books"
authors = "VinnyStalck"
description = '''
Patchouli books for vanilla.
'''
#logoFile = ""

[[dependencies.knowledgebooks]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.knowledgebooks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.knowledgebooks]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.knowledgebooks]]
modId = "patchouli"
mandatory = true
versionRange = "[1.16.4-50,)"
ordering = "AFTER"
side = "BOTH"